"""
招标文件分析特征库
定义友商品牌关键词、施耐德品牌关键词、招标文件章节关键词，用于检测标书中的品牌植入情况。
所有关键词均来源于现有产品样本和FAQ知识库，确保真实可查。
"""

# ============================================================
# 友商特征 — 检测标书中是否出现友商品牌
# 每个友商包含：品牌名称、关键词列表、独有系列型号
# ============================================================
COMPETITOR_FEATURES = {
    "西门子": {
        "brand": "西门子",
        "keywords": [
            "西门子", "西門子", "镇江西门子",
            "SIEMENS", "Siemens",
            "XL-IIIS", "XL-IIIS密集型",
            "XL-III", "XLC-III", "XLC-IIIH",
            "XLB-III", "XLB-III铝合金",
            "XL-ⅡS", "XL-IIS",
        ],
        "series": ["XL-IIIS", "XL-III", "XLB-III", "XLC-IIIH", "XL-ⅡS"],
        "unique_params": [],
    },
    "伊顿": {
        "brand": "伊顿",
        "keywords": [
            "伊顿", "Eaton", "EATON",
            "XAP-B", "XAP-C", "XAP-HR", "XAP-HS", "XAP-J", "XAP-S",
            "XAP Track", "XAP Track Pro",
            "伊顿XAP", "伊顿母线",
        ],
        "series": ["XAP-B", "XAP-C", "XAP-HR", "XAP-HS", "XAP-J", "XAP-S", "XAP Track", "XAP Track Pro"],
        "unique_params": [],
    },
    "ABB": {
        "brand": "ABB",
        "keywords": ["ABB", "ABB母线", "ABB Busway"],
        "series": [],
        "unique_params": [],
    },
    "LS": {
        "brand": "LS",
        "keywords": ["LS", "LG", "LS母线", "LS电缆", "韩国LS"],
        "series": [],
        "unique_params": [],
    },
    "罗格朗": {
        "brand": "罗格朗",
        "keywords": ["罗格朗", "Legrand", "罗格朗母线"],
        "series": [],
        "unique_params": [],
    },
    "正泰": {
        "brand": "正泰",
        "keywords": ["正泰", "正泰母线", "CHINT", "Chint"],
        "series": [],
        "unique_params": [],
    },
    "德力西": {
        "brand": "德力西",
        "keywords": ["德力西", "DELIXI", "德力西母线"],
        "series": [],
        "unique_params": [],
    },
}

# ============================================================
# 施耐德特征 — 检测标书中是否已有施耐德品牌植入
# ============================================================
SCHNEIDER_FEATURES = {
    "brand": "施耐德",
    "keywords": [
        "施耐德", "Schneider", "SCHNEIDER", "施耐德电气",
        "I-Line", "I-LINE", "Iline",
        "I-Line H", "I-Line HL", "I-Line HN",
        "I-Line V", "I-Line W", "I-Line C", "I-Line B",
        "Canalis", "CANALIS",
        "Square D", "SQUARE D",
        "施耐德母线", "施耐德广州",
    ],
    "series": [
        "I-Line H", "I-Line HL", "I-Line HN",
        "I-Line V", "I-Line W", "I-Line C", "I-Line B",
        "Canalis",
    ],
    "required_certifications": [
        "KEMA", "KEMA-KEUR", "CE",
    ],
}

# ============================================================
# 招标文件章节关键词 — 用于定位关键章节
# ============================================================
TENDER_SECTIONS = {
    "技术参数": ["技术参数", "参数表", "规格参数", "技术要求", "技术规格", "性能参数"],
    "资质要求": ["资质要求", "认证要求", "资格条件", "投标人资格", "资格审查"],
    "投标基本资料": ["投标基本资料", "基本资料", "投标资料", "需提供的资料", "应提交的资料", "提交资料"],
    "评分标准": ["评分标准", "评标办法", "打分标准", "评审办法", "综合评分"],
    "业绩要求": ["业绩要求", "工程经验", "类似业绩", "项目业绩", "同类项目"],
    "供货范围": ["供货范围", "供货清单", "货物清单", "设备清单", "供货一览表"],
    "付款方式": ["付款方式", "付款条件", "结算方式", "支付方式"],
    "保修条款": ["保修", "质保", "售后服务", "维护保养", "保修期"],
}

# ============================================================
# 投标常用文件清单 — 根据分析结果推荐下载的文件
# ============================================================
REQUIRED_DOCUMENTS = {
    # 基础资质文件
    "营业执照": {"key": "business_license", "description": "营业执照副本（加盖公章）"},
    "ISO认证": {"key": "iso_cert", "description": "ISO 9001质量管理体系认证证书"},
    "CE认证": {"key": "ce_cert", "description": "CE认证证书"},
    "KEMA认证": {"key": "kema_cert", "description": "KEMA-KEUR认证证书"},
    "产品检测报告": {"key": "test_report", "description": "国家认可实验室出具的产品检测报告"},
    "业绩证明": {"key": "performance", "description": "近三年类似项目业绩证明"},
    "产品样本": {"key": "product_catalog", "description": "产品电子版样本（I-Line B/C/H/HL/HN/V/W 系列）"},
    "法人授权书": {"key": "authorization", "description": "法定代表人授权委托书"},
    "投标函": {"key": "bid_letter", "description": "投标函"},
    "报价表": {"key": "price_list", "description": "投标报价表"},
    # 投标基本资料 — 具体检测报告与资质证明
    "母线槽整体型式试验报告": {"key": "type_test_report", "description": "母线槽整体型式试验报告（CCC认证）"},
    "铜材第三方检测报告": {"key": "copper_test_report", "description": "母线槽所用铜材第三方检测报告"},
    "绝缘材料第三方检测报告": {"key": "insulation_test_report", "description": "母线槽所用绝缘材料第三方检测报告"},
    "绝缘材料阻燃报告": {"key": "insulation_flame_report", "description": "母线槽所用绝缘材料阻燃报告"},
    "外壳盐雾试验报告": {"key": "salt_spray_report", "description": "母线槽外壳1800小时或以上盐雾试验报告"},
    "制造商制造经验证明": {"key": "manufacturing_experience", "description": "制造商具备5年或以上相关制造经验证明材料"},
    # 新增资料类型
    "抗震测试报告": {"key": "seismic_report", "description": "母线槽抗震测试报告（UBC/AG5标准）"},
    "消防喷淋检测报告": {"key": "fire_spray_report", "description": "母线槽1小时消防喷淋检测报告"},
    "耐火检测报告": {"key": "fire_resistance_report", "description": "母线槽耐火检测报告（XF/T537/J19216）"},
    "OHSAS认证": {"key": "ohsas_cert", "description": "OHSAS18001/ISO45001职业健康安全管理体系认证"},
    "带电插拔检测报告": {"key": "hot_swap_report", "description": "插接箱带电热插拔检测报告"},
    "连接器力矩测试报告": {"key": "torque_test_report", "description": "连接器力矩测试报告（≥80N.m）"},
    "IK碰撞等级测试报告": {"key": "ik_rating_report", "description": "外壳IK碰撞等级测试报告"},
    "CQC节能认证": {"key": "cqc_energy_cert", "description": "CQC节能认证证书"},
    "RoHS环保认证": {"key": "rohs_cert", "description": "RoHS环保认证证书"},
    "智能监测功能证明": {"key": "monitoring_cert", "description": "智能监测单元功能证明"},
}

# 投标基本资料关键词 — 用于检测标书中是否要求这些具体资料
# 扩展版：覆盖更多资料类型，支持同义词匹配
TENDER_BIDDING_REQUIREMENTS = {
    "母线槽整体型式试验报告": [
        "型式试验报告", "型式试验", "CCC报告", "CCC认证", "3C认证", "强制认证", "型式检验",
        "CCC型式试验", "3C型式试验", "强制认证报告", "CCC型式检验", "国家强制性产品认证",
        "国家权威机构出具的型式试验报告", "国家权威机构出具有效的型式试验报告",
    ],
    "铜材第三方检测报告": [
        "铜材检测", "铜纯度", "铜材第三方", "铜导体检测", "导体铜含量", "铜材报告",
        "铜材测试", "铜材检验", "铜排检测", "铜排测试", "铜排纯度", "铜导体纯度",
        "铜材第三方检测", "铜材检测报告",
    ],
    "绝缘材料第三方检测报告": [
        "绝缘材料检测", "绝缘材料第三方", "绝缘材料测试", "绝缘强度", "绝缘电阻",
        "绝缘材料检验", "绝缘报告", "绝缘检测", "绝缘测试",
    ],
    "绝缘材料阻燃报告": [
        "阻燃报告", "阻燃检测", "阻燃试验", "阻燃等级", "防火等级", "耐火等级", "火焰蔓延",
        "阻燃测试", "阻燃检验", "阻燃性能",
    ],
    "外壳盐雾试验报告": [
        "盐雾试验", "盐雾测试", "耐腐蚀", "盐雾", "1800小时", "防腐试验", "防腐测试",
        "盐雾报告", "耐腐蚀报告", "盐雾检测", "盐雾等级", "盐雾认证",
    ],
    "制造商制造经验证明": [
        "制造经验", "生产经验", "成立年限", "经营年限", "制造商资格", "制造商资质",
        "从事母线", "制造历史", "制造经验证明", "生产经验证明", "制造商经验",
    ],
    "产品样本": [
        "产品样本", "产品手册", "产品说明", "产品目录", "产品选型", "样本册", "技术手册", "样本图册",
        "产品介绍", "产品资料", "产品技术资料",
    ],
    # ---- 新增资料类型（扩展覆盖率） ----
    "抗震测试报告": [
        "抗震测试", "抗震试验", "抗震检测", "地震测试", "抗震报告", "UBC", "抗震设防",
        "抗震等级", "抗震认证", "抗震鉴定",
    ],
    "消防喷淋检测报告": [
        "消防喷淋", "喷淋试验", "喷淋测试", "消防水试验", "消防喷淋检测",
        "喷淋检测报告", "消防喷淋试验", "喷淋检测", "消防喷淋报告",
    ],
    "耐火检测报告": [
        "耐火试验", "耐火测试", "耐火检测", "耐火报告", "耐火等级", "XF/T537", "J19216",
        "耐火认证", "耐火时间", "耐火极限",
    ],
    "OHSAS认证": [
        "OHSAS18001", "OHSAS", "ISO45001", "职业健康安全", "职业健康",
        "OHSAS 18001", "ISO 45001",
    ],
    "带电插拔检测报告": [
        "带电插拔", "热插拔", "带电热插拔", "即插即用", "带电插拔检测", "热插拔测试",
    ],
    "连接器力矩测试报告": [
        "力矩测试", "力矩检测", "扭矩测试", "力矩螺栓", "力矩报告", "力矩试验", "扭矩检测",
    ],
    "IK碰撞等级测试报告": [
        "IK测试", "IK检测", "IK等级", "IK10", "IK08", "碰撞测试", "碰撞等级", "机械碰撞测试",
    ],
    "CQC节能认证": [
        "CQC", "节能认证", "节能产品", "能效认证", "CQC认证", "节能检测",
    ],
    "RoHS环保认证": [
        "RoHS", "环保认证", "有害物质", "环保要求", "RoHS认证", "RoHS检测",
    ],
    "ISO认证": [
        "ISO9001", "ISO 9001", "ISO9001-2000", "ISO 9001-2000",
        "ISO9001-14000", "ISO 9001-14000", "ISO14001", "ISO 14001",
        "质量管理体系", "质量体系认证", "质量体系",
    ],
    "CE认证": [
        "CE认证", "CE证书", "CE mark", "CE marking",
    ],
    "KEMA认证": [
        "KEMA", "KEMA-KEUR", "ASTA", "ASTA-DIAMOND",
        "国际认证", "KEMA认证", "ASTA认证",
    ],
    "营业执照": [
        "营业执照", "工商注册", "营业执照副本",
    ],
    "智能监测功能证明": [
        "智能监测", "监测单元", "温度监测", "谐波监测", "RS485", "全电量",
        "智能监测功能", "智能监测证明",
    ],
}

# ============================================================
# 产品系列技术特征 — 用于智能分析中匹配招标文件与产品
# 数据来源于 I-Line B/H/W 技术规范书
# ============================================================
PRODUCT_SERIES = {
    "I-Line B": {
        "full_name": "I-Line B 系列密集型母线槽",
        "positioning": "中高端通用型，技术参数均衡",
        "conductor": "铜导体，电气连接部位镀银",
        "seismic": "AG5 (ZPA=0.5g)，里氏7级，烈度9级",
        "salt_spray": "1800小时",
        "r20_resistance": "有R20电阻限值表",
        "kema": "KEMA-KEUR认证",
        "cqc_energy": "CQC节能认证（全系列）",
        "manufacturer_years": "15年以上",
        "connector_torque": "≥95N.m",
        "connector_current": "连接头载流提升至少40%",
        "insulation_aging": "绝缘材料5000小时老化测试",
        "fire_spray": "1小时消防喷淋检测报告",
        "ik_rating": "插接箱可选IK10",
        "ip_rating": "插接箱可选IP55",
        "oem_policy": "禁止OEM/贴牌，申请人/制造商/生产企业三者一致",
        "no_double_splice": "禁止外双拼结构",
        "heavy_load": "外壳90KG重载测试",
        "rohs": "RoHS环保认证",
        "plug_interface": "插接口通用（63A-1250A）",
        "silver_contact": "插接箱银-银接触",
        "ground_ccc": "地线系统与CCC报告一致",
        "neutral": "100%中性线容量",
        "anti_chimney": "防烟囱效应",
        "monitoring": "智能监测单元（全电量、谐波、温度、RS485）",
        "hot_swap": "插接箱带电热插拔",
        "structure": "密集型三明治结构",
        "drainage": "外壳排水孔设计",
    },
    "I-Line H": {
        "full_name": "I-Line H 系列密集型母线槽",
        "positioning": "高端旗舰型，参数最严格，全长镀银",
        "conductor": "铜导体，全长镀银",
        "seismic": "AG5 (ZPA=0.5g)，里氏7级，烈度9级",
        "salt_spray": "2000小时",
        "r20_resistance": "有R20电阻限值表（更严格）",
        "kema": "KEMA-KEUR认证",
        "cqc_energy": "CQC节能认证（全系列）",
        "manufacturer_years": "15年以上",
        "connector_torque": "≥80N.m",
        "connector_current": "连接头双面搭接",
        "insulation_aging": "绝缘材料5000小时老化测试",
        "fire_spray": "1小时消防喷淋检测报告",
        "ik_rating": "IK10",
        "ip_rating": "IP54~IP66可选",
        "oem_policy": "禁止OEM/贴牌，申请人/制造商/生产企业三者一致",
        "no_double_splice": "禁止外双拼结构",
        "conductor_thickness": "导体厚度≥4mm",
        "rohs": "RoHS环保认证",
        "plug_interface": "800A及以下插接口标准化，双插爪",
        "silver_contact": "插接箱银-银接触",
        "ground_ccc": "地线系统与CCC报告一致",
        "neutral": "100%中性线容量",
        "anti_chimney": "防烟囱效应（有第三方报告）",
        "monitoring": "智能监测单元（全电量、谐波、温度、RS485）",
        "hot_swap": "插接箱带电热插拔",
        "structure": "密集型三明治结构",
        "drainage": "外壳排水孔设计",
    },
    "I-Line W": {
        "full_name": "I-Line W 系列密集型母线槽",
        "positioning": "通用型，参数适中，成本合理",
        "conductor": "铜导体，电气搭接处镀银",
        "seismic": "标准抗震（未明确AG5）",
        "salt_spray": "1800小时",
        "r20_resistance": "符合标准要求",
        "kema": "KEMA-KEUR认证",
        "cqc_energy": "CQC节能认证",
        "manufacturer_years": "15年以上",
        "connector_torque": "≥80N.m",
        "connector_current": "连接头载流提升至少30%",
        "insulation_aging": "绝缘材料老化测试",
        "fire_spray": "消防喷淋检测",
        "ik_rating": "标准IK等级",
        "ip_rating": "IP54",
        "oem_policy": "制造商/生产企业一致性",
        "no_double_splice": "标准结构",
        "rohs": "RoHS环保认证",
        "plug_interface": "标准插接口",
        "silver_contact": "插接箱银-银接触",
        "ground_ccc": "地线系统与CCC报告一致",
        "neutral": "100%中性线容量",
        "anti_chimney": "防烟囱效应",
        "monitoring": "智能监测单元（全电量、谐波、温度、RS485）",
        "hot_swap": "插接箱带电热插拔",
        "structure": "密集型三明治结构",
        "drainage": "外壳排水孔设计",
    },
}

# ============================================================
# 施耐德有利条款检测 — 如果招标文件中出现这些条款，说明已有我方植入
# 每条包含：条款名称、检测关键词、风险等级（缺失时）、所属产品系列
# ============================================================
FAVORABLE_CLAUSES = [
    {
        "id": "seismic_ag5",
        "name": "抗震要求AG5",
        "keywords": ["抗震", "AG5", "ZPA", "里氏", "烈度", "地震", "抗震等级"],
        "favorable_threshold": "AG5及以上或ZPA≥0.5g或里氏7级",
        "risk_if_missing": "高",
        "analysis_favorable": "抗震AG5要求为我方I-Line B/H核心技术壁垒，多数友商无法满足",
        "analysis_missing": "未要求抗震等级，友商中低端产品可直接投标，我方抗震优势无法体现",
        "products": ["I-Line B", "I-Line H"],
    },
    {
        "id": "conductor_silver_full",
        "name": "导体全长镀银",
        "keywords": ["全长镀银", "全段镀银", "导体镀银", "镀银层", "全长镀"],
        "favorable_threshold": "全长镀银",
        "risk_if_missing": "中",
        "analysis_favorable": "全长镀银为我方I-Line H独有优势，极大提高友商成本",
        "analysis_missing": "未要求全长镀银，仅要求镀锡或局部镀银，友商低成本产品可满足",
        "products": ["I-Line H"],
    },
    {
        "id": "conductor_silver",
        "name": "导体镀银要求",
        "keywords": ["镀银", "镀锡", "导体镀层", "铜排镀层", "导体表面"],
        "favorable_threshold": "至少连接处镀银",
        "risk_if_missing": "中",
        "analysis_favorable": "要求镀银可提升我方产品竞争力",
        "analysis_missing": "仅要求镀锡或不明确，低成本竞品可满足",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "kema_asta",
        "name": "KEMA/ASTA国际认证",
        "keywords": ["KEMA", "ASTA", "KEMA-KEUR", "ASTA-DIAMOND", "国际认证", "型式认证"],
        "favorable_threshold": "要求KEMA-KEUR或ASTA-DIAMOND认证",
        "risk_if_missing": "高",
        "analysis_favorable": "KEMA/ASTA为我方国际认证优势，多数国内友商不具备",
        "analysis_missing": "未要求国际认证，我方认证优势被忽略",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "cqc_energy",
        "name": "CQC节能认证",
        "keywords": ["CQC", "节能认证", "节能产品", "能效认证"],
        "favorable_threshold": "要求CQC节能认证",
        "risk_if_missing": "中",
        "analysis_favorable": "CQC节能认证为我方全系列具备的优势",
        "analysis_missing": "未要求节能认证，无法体现我方能效优势",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "manufacturer_years",
        "name": "制造商经验年限",
        "keywords": ["制造经验", "生产经验", "成立年限", "经营年限", "从事母线", "制造商资格"],
        "favorable_threshold": "要求15年以上",
        "risk_if_missing": "高",
        "analysis_favorable": "15年以上要求大幅限制新进入者和OEM厂商",
        "analysis_missing": "仅要求5年或未要求，允许大量中小厂商进入",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "oem_policy",
        "name": "禁止OEM/贴牌",
        "keywords": ["OEM", "贴牌", "申请人", "制造商一致", "生产企业一致", "三者一致", "同一主体"],
        "favorable_threshold": "要求申请人/制造商/生产企业三者一致",
        "risk_if_missing": "高",
        "analysis_favorable": "禁止OEM可屏蔽大量贴牌厂商",
        "analysis_missing": "未要求三者一致，允许OEM/贴牌厂商参与",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "salt_spray_1800",
        "name": "盐雾试验≥1800小时",
        "keywords": ["盐雾", "盐雾试验", "盐雾测试", "耐腐蚀", "防腐"],
        "favorable_threshold": "要求1800小时及以上",
        "risk_if_missing": "中",
        "analysis_favorable": "1800小时盐雾要求可屏蔽多数中低端竞品",
        "analysis_missing": "仅要求1000小时或未要求，降低防腐门槛",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "fire_spray",
        "name": "1小时消防喷淋试验",
        "keywords": ["消防喷淋", "喷淋试验", "消防试验", "喷淋测试", "消防水"],
        "favorable_threshold": "要求1小时消防喷淋检测报告",
        "risk_if_missing": "高",
        "analysis_favorable": "1小时消防喷淋为我方重要防水优势",
        "analysis_missing": "未要求消防喷淋试验，我方防水优势被忽略",
        "products": ["I-Line B", "I-Line H"],
    },
    {
        "id": "no_double_splice",
        "name": "禁止外双拼结构",
        "keywords": ["双拼", "外双拼", "双拼结构", "拼接", "拼装"],
        "favorable_threshold": "明确禁止外双拼结构",
        "risk_if_missing": "中",
        "analysis_favorable": "禁止双拼可屏蔽低成本竞品",
        "analysis_missing": "未禁止双拼，竞品可用低成本双拼结构",
        "products": ["I-Line B", "I-Line H"],
    },
    {
        "id": "insulation_aging",
        "name": "绝缘材料老化测试",
        "keywords": ["绝缘老化", "老化测试", "老化试验", "绝缘材料", "5000小时"],
        "favorable_threshold": "要求5000小时老化测试",
        "risk_if_missing": "中",
        "analysis_favorable": "5000小时老化测试要求极大提高绝缘材料门槛",
        "analysis_missing": "未要求老化测试，降低绝缘材料门槛",
        "products": ["I-Line B", "I-Line H"],
    },
    {
        "id": "connector_torque",
        "name": "连接头力矩要求",
        "keywords": ["力矩", "力矩螺栓", "N.m", "N·m", "扭矩", "力矩要求"],
        "favorable_threshold": "≥80N.m",
        "risk_if_missing": "低",
        "analysis_favorable": "力矩螺栓要求确保连接可靠性",
        "analysis_missing": "未明确力矩要求，连接可靠性无保障",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "connector_current",
        "name": "连接头载流提升",
        "keywords": ["载流提升", "载流能力", "双面搭接", "连接器载流", "连接头载流"],
        "favorable_threshold": "要求载流提升30%以上",
        "risk_if_missing": "中",
        "analysis_favorable": "载流提升要求可屏蔽连接器性能不足的竞品",
        "analysis_missing": "未要求载流提升，降低连接器性能门槛",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "ik_rating",
        "name": "IK碰撞防护等级",
        "keywords": ["IK", "碰撞", "IK10", "IK08", "机械碰撞", "抗碰撞"],
        "favorable_threshold": "要求IK10",
        "risk_if_missing": "中",
        "analysis_favorable": "IK10要求可屏蔽外壳强度不足的竞品",
        "analysis_missing": "未要求IK等级，降低外壳防护门槛",
        "products": ["I-Line B", "I-Line H"],
    },
    {
        "id": "ip_rating",
        "name": "IP防护等级",
        "keywords": ["IP54", "IP55", "IP65", "IP66", "防护等级", "外壳防护"],
        "favorable_threshold": "要求IP55及以上",
        "risk_if_missing": "低",
        "analysis_favorable": "高IP等级要求可屏蔽防护能力不足的竞品",
        "analysis_missing": "仅要求IP54，中低端竞品可满足",
        "products": ["I-Line B", "I-Line H"],
    },
    {
        "id": "r20_resistance",
        "name": "导体电阻R20限值",
        "keywords": ["R20", "电阻", "电阻限值", "导体电阻", "mΩ/m", "电阻值"],
        "favorable_threshold": "列出R20电阻限值表",
        "risk_if_missing": "高",
        "analysis_favorable": "R20电阻限值要求可屏蔽使用低导电率铜材的竞品",
        "analysis_missing": "未列出R20限值，友商可用低铜排厚度/导电率产品混标",
        "products": ["I-Line B", "I-Line H"],
    },
    {
        "id": "plug_interface",
        "name": "插接口标准化",
        "keywords": ["插接口", "插接箱通用", "插接口通用", "标准化插口", "通用插口"],
        "favorable_threshold": "要求插接口标准化/通用化",
        "risk_if_missing": "中",
        "analysis_favorable": "标准化插接口要求可屏蔽非标插口竞品",
        "analysis_missing": "未明确标准化要求，友商可用非标插口",
        "products": ["I-Line B", "I-Line H"],
    },
    {
        "id": "silver_contact",
        "name": "银-银接触",
        "keywords": ["银-银", "银接触", "银银", "镀银接触", "插接爪"],
        "favorable_threshold": "要求银-银接触",
        "risk_if_missing": "低",
        "analysis_favorable": "银-银接触确保插接可靠性",
        "analysis_missing": "未要求银-银接触，插接可靠性无保障",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "rohs",
        "name": "RoHS环保认证",
        "keywords": ["RoHS", "环保认证", "有害物质", "环保要求"],
        "favorable_threshold": "要求RoHS认证",
        "risk_if_missing": "低",
        "analysis_favorable": "RoHS认证体现环保优势",
        "analysis_missing": "未要求RoHS认证",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "heavy_load",
        "name": "外壳重载测试",
        "keywords": ["重载", "90KG", "90kg", "重载测试", "负重测试", "承载测试"],
        "favorable_threshold": "要求外壳重载测试",
        "risk_if_missing": "低",
        "analysis_favorable": "外壳重载测试要求可体现结构强度优势",
        "analysis_missing": "未要求重载测试",
        "products": ["I-Line B"],
    },
    {
        "id": "conductor_thickness",
        "name": "导体厚度要求",
        "keywords": ["导体厚度", "铜排厚度", "导体截面", "导电排厚度", "≥4mm"],
        "favorable_threshold": "要求导体厚度≥4mm",
        "risk_if_missing": "中",
        "analysis_favorable": "导体厚度≥4mm要求可屏蔽使用薄铜排的竞品",
        "analysis_missing": "未要求导体厚度，竞品可用薄铜排降低成本",
        "products": ["I-Line H"],
    },
    {
        "id": "monitoring",
        "name": "智能监测单元",
        "keywords": ["智能监测", "监测单元", "温度监测", "谐波监测", "RS485", "全电量"],
        "favorable_threshold": "要求智能监测单元",
        "risk_if_missing": "低",
        "analysis_favorable": "智能监测单元为我方成熟方案",
        "analysis_missing": "未要求智能监测",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
    {
        "id": "anti_chimney",
        "name": "防烟囱效应",
        "keywords": ["烟囱效应", "防烟囱", "防火封堵", "阻火", "烟囱"],
        "favorable_threshold": "要求防烟囱效应",
        "risk_if_missing": "低",
        "analysis_favorable": "防烟囱效应为我方标配",
        "analysis_missing": "未要求防烟囱效应",
        "products": ["I-Line B", "I-Line H", "I-Line W"],
    },
]

# ============================================================
# 友商风险指标 — 检测招标文件中可能存在的友商植入痕迹
# ============================================================
COMPETITOR_RISK_INDICATORS = [
    {
        "id": "low_salt_spray",
        "name": "盐雾试验要求过低",
        "keywords": ["盐雾", "1000小时", "盐雾试验"],
        "risk_pattern": "仅要求1000小时或以下",
        "risk_level": "中",
        "analysis": "1000小时盐雾要求过低，可能为友商（特别是中低端品牌）故意降低门槛",
        "possible_competitor": "中低端竞品",
    },
    {
        "id": "low_manufacturer_years",
        "name": "制造商经验年限过低",
        "keywords": ["制造经验", "5年", "从事母线"],
        "risk_pattern": "要求5年或以下",
        "risk_level": "高",
        "analysis": "仅要求5年制造经验，大幅降低制造商门槛，可能为友商故意弱化",
        "possible_competitor": "新进入者/中小厂商",
    },
    {
        "id": "allow_oem",
        "name": "允许OEM/贴牌",
        "keywords": ["OEM", "贴牌", "代理", "授权生产"],
        "risk_pattern": "允许OEM或贴牌生产",
        "risk_level": "高",
        "analysis": "允许OEM/贴牌，可能为友商（贴牌厂商）故意保留的条款",
        "possible_competitor": "贴牌/代理厂商",
    },
    {
        "id": "allow_double_splice",
        "name": "允许双拼结构",
        "keywords": ["双拼", "拼接", "拼装"],
        "risk_pattern": "允许或不禁止双拼结构",
        "risk_level": "中",
        "analysis": "允许双拼结构，有利于使用低成本双拼方案的友商",
        "possible_competitor": "国内低价品牌",
    },
    {
        "id": "tin_only",
        "name": "仅要求镀锡",
        "keywords": ["镀锡", "镀锡层", "镀锡处理"],
        "risk_pattern": "仅要求镀锡，未要求镀银",
        "risk_level": "中",
        "analysis": "仅要求镀锡可能为友商故意降低导体镀层要求，降低成本",
        "possible_competitor": "中低端竞品",
    },
    {
        "id": "no_kema",
        "name": "未要求国际认证",
        "keywords": ["CCC", "3C", "型式试验"],
        "risk_pattern": "仅要求CCC认证，未要求KEMA/ASTA",
        "risk_level": "高",
        "analysis": "仅要求CCC认证可能为友商故意排除国际认证要求",
        "possible_competitor": "国内友商",
    },
    {
        "id": "alloy_conductor",
        "name": "要求合金导体",
        "keywords": ["合金导体", "铝合金", "合金", "铜铝复合"],
        "risk_pattern": "要求使用合金导体而非纯铜导体",
        "risk_level": "高",
        "analysis": "合金导体要求可能为友商（特别是铝合金母线厂商）的定向植入",
        "possible_competitor": "合金/铝母线厂商",
    },
    {
        "id": "low_ip",
        "name": "IP防护等级过低",
        "keywords": ["IP54", "IP42", "IP30", "防护等级"],
        "risk_pattern": "仅要求IP54或以下",
        "risk_level": "低",
        "analysis": "IP防护等级要求过低，降低外壳防护门槛",
        "possible_competitor": "中低端竞品",
    },
    {
        "id": "no_fire_spray",
        "name": "未要求消防喷淋",
        "keywords": ["消防", "喷淋", "防火"],
        "risk_pattern": "未提及消防喷淋试验",
        "risk_level": "高",
        "analysis": "未要求消防喷淋试验，可能为友商故意排除我方防水优势",
        "possible_competitor": "不具备消防喷淋能力的友商",
    },
    {
        "id": "no_seismic",
        "name": "未要求抗震等级",
        "keywords": ["抗震", "地震", "震动"],
        "risk_pattern": "未提及抗震要求",
        "risk_level": "高",
        "analysis": "未要求抗震等级，可能为友商故意排除我方抗震优势",
        "possible_competitor": "不具备抗震认证的友商",
    },
]